/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMyHistoryRouteImport } from './routes/_authenticated/my-history'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedBorrowsRouteImport } from './routes/_authenticated/borrows'
import { Route as AuthenticatedBorrowRouteImport } from './routes/_authenticated/borrow'
import { Route as AuthenticatedBooksRouteImport } from './routes/_authenticated/books'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyHistoryRoute = AuthenticatedMyHistoryRouteImport.update({
  id: '/my-history',
  path: '/my-history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBorrowsRoute = AuthenticatedBorrowsRouteImport.update({
  id: '/borrows',
  path: '/borrows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBorrowRoute = AuthenticatedBorrowRouteImport.update({
  id: '/borrow',
  path: '/borrow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBooksRoute = AuthenticatedBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/books': typeof AuthenticatedBooksRoute
  '/borrow': typeof AuthenticatedBorrowRoute
  '/borrows': typeof AuthenticatedBorrowsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/my-history': typeof AuthenticatedMyHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/books': typeof AuthenticatedBooksRoute
  '/borrow': typeof AuthenticatedBorrowRoute
  '/borrows': typeof AuthenticatedBorrowsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/my-history': typeof AuthenticatedMyHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/books': typeof AuthenticatedBooksRoute
  '/_authenticated/borrow': typeof AuthenticatedBorrowRoute
  '/_authenticated/borrows': typeof AuthenticatedBorrowsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/my-history': typeof AuthenticatedMyHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/books'
    | '/borrow'
    | '/borrows'
    | '/members'
    | '/my-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/books'
    | '/borrow'
    | '/borrows'
    | '/members'
    | '/my-history'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/books'
    | '/_authenticated/borrow'
    | '/_authenticated/borrows'
    | '/_authenticated/members'
    | '/_authenticated/my-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-history': {
      id: '/_authenticated/my-history'
      path: '/my-history'
      fullPath: '/my-history'
      preLoaderRoute: typeof AuthenticatedMyHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrows': {
      id: '/_authenticated/borrows'
      path: '/borrows'
      fullPath: '/borrows'
      preLoaderRoute: typeof AuthenticatedBorrowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/borrow': {
      id: '/_authenticated/borrow'
      path: '/borrow'
      fullPath: '/borrow'
      preLoaderRoute: typeof AuthenticatedBorrowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/books': {
      id: '/_authenticated/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBooksRoute: typeof AuthenticatedBooksRoute
  AuthenticatedBorrowRoute: typeof AuthenticatedBorrowRoute
  AuthenticatedBorrowsRoute: typeof AuthenticatedBorrowsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedMyHistoryRoute: typeof AuthenticatedMyHistoryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBooksRoute: AuthenticatedBooksRoute,
  AuthenticatedBorrowRoute: AuthenticatedBorrowRoute,
  AuthenticatedBorrowsRoute: AuthenticatedBorrowsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedMyHistoryRoute: AuthenticatedMyHistoryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
